name: doctor_finder
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # local storage
  shared_preferences: ^2.5.3
  # routing
  go_router: ^15.1.3
  # state management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  # UI
  image_picker: ^1.1.2
  # firebase backend capabilities
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  firebase_storage: ^12.4.7
  cloud_firestore: ^5.6.9
  # google map functionality
  geolocator: ^14.0.1
  google_places_flutter: ^2.1.0
  flutter_google_maps_webservices: ^1.1.1
  # secure environment variables
  flutter_dotenv: ^5.2.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.5
  flutter_gen_runner: ^5.10.0

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/fonts/
    - .env

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700