// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2hWAREXhLEMoI6ViD73R1hEdHvnp5Mzs',
    appId: '1:956602096437:web:6b14c3f4d779fd0a7e4a7c',
    messagingSenderId: '956602096437',
    projectId: 'doctor-finder-c4a42',
    authDomain: 'doctor-finder-c4a42.firebaseapp.com',
    storageBucket: 'doctor-finder-c4a42.firebasestorage.app',
    measurementId: 'G-ELD6C0GXX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnXmxHK_PvSX-MZZ3OLIbLs66t7dCX7jM',
    appId: '1:956602096437:android:b08b2684609aee3d7e4a7c',
    messagingSenderId: '956602096437',
    projectId: 'doctor-finder-c4a42',
    storageBucket: 'doctor-finder-c4a42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu2OgRnNhT84xLfeVspY7rl__NkL6fg34',
    appId: '1:956602096437:ios:af015b502627b09b7e4a7c',
    messagingSenderId: '956602096437',
    projectId: 'doctor-finder-c4a42',
    storageBucket: 'doctor-finder-c4a42.firebasestorage.app',
    iosBundleId: 'com.manishsoni.doctorFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu2OgRnNhT84xLfeVspY7rl__NkL6fg34',
    appId: '1:956602096437:ios:af015b502627b09b7e4a7c',
    messagingSenderId: '956602096437',
    projectId: 'doctor-finder-c4a42',
    storageBucket: 'doctor-finder-c4a42.firebasestorage.app',
    iosBundleId: 'com.manishsoni.doctorFinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2hWAREXhLEMoI6ViD73R1hEdHvnp5Mzs',
    appId: '1:956602096437:web:690a113b37ff6aa17e4a7c',
    messagingSenderId: '956602096437',
    projectId: 'doctor-finder-c4a42',
    authDomain: 'doctor-finder-c4a42.firebaseapp.com',
    storageBucket: 'doctor-finder-c4a42.firebasestorage.app',
    measurementId: 'G-R95EWQ1M1G',
  );
}
